### ISSUE TITLE
Expose State(..) in Bootstrap.Tab

### ISSUE THREAD

**Issue by samlee64** [rundis/elm-bootstrap#160] opened 2019-05-15 22:54 UTC
```
module Bootstrap.Tab exposing
    ( view, config, items, initialState, customInitialState, Config, State
    , pills, withAnimation, justified, fill, center, right, attrs, useHash, Option
    , item, link, pane, Item, Link, Pane
    , subscriptions
    )
```
State is currently an opaque type. Could we expose all of State so that I am able to grab what the active tab is?

**Comment by rundis** [comment] 2019-07-30 13:36
Whats the use case? Typically you would use elm navigation in most web apps, then you can keep track of the id of the active tab explicitly in your own state by handling navigation events and pick out the hash from the url passed in.

**Comment by rundis** [comment] 2019-08-03 13:19
Duplicate of #65

**Closed by rundis** 2019-08-03 13:19 UTC
