### ISSUE TITLE
When I use the navbar I see "ScreenSize: XL" written to console

### ISSUE THREAD

**Issue by rcook** [rundis/elm-bootstrap#112] opened 2018-06-16 19:20 UTC
1. Build Elm app using Bootstrap navbar
2. Open debugger in browser such as Google Chrome
3. Load Elm app

Observe: "ScreenSize: XL" or similar output to debugger console.

It doesn't stop the app working, but it is noisy when I'm debugging.

If this is an artifact of Bootstrap itself, please close this issue!

**Comment by rundis** [comment] 2018-06-16 19:56
Duplicate of https://github.com/rundis/elm-bootstrap/issues/90

**Closed by rundis** 2018-06-16 19:56 UTC
